package com.example.drivinglicenceadmin

const val TOKEN = "TOKEN"
const val KEY_EXAM = "KEY_EXAM"
const val KEY_NEW_EXAM = "KEY_NEW_EXAM"
const val KEY_UPDATE_EXAM = "KEY_UPDATE_EXAM"
const val KEY_PASS_EXAM = "KEY_PASS_EXAM"
const val KEY_QUESTION = "KEY_QUESTION"
const val KEY_UPDATE_QUESTION = "KEY_UPDATE_QUESTION"
const val KEY_NEW_QUESTION = "KEY_NEW_QUESTION"
const val KEY_PASS_QUESTION = "KEY_PASS_QUESTION"
const val KEY_REQUEST_CAMERA = 100
const val ACCOUNT = "USER"
const val KEY_TYPE = "KEY_TYPE"
const val KEY_PASS_TYPE = "KEY_PASS_TYPE"
const val KEY_PASS_RESULT_QUESTION = "KEY_PASS_RESULT_QUESTION"
const val KEY_DO_OR_RESULT = "KEY_DO_OR_RESULT"
const val KEY_DO_EXAM = "KEY_DO_EXAM"
const val KEY_SEE_RESULT = "KEY_SEE_RESULT"
const val RESULT_QUESTION = "RESULT_QUESTION"
const val TYPE_ANOTHER: Long = 15
const val KEY_LEARN = "KEY_LEARN"